In [8]:
# Ncore = random.randint(1, 10)
Ncore = 10
Ntasks = 400
Ri_para = 3
N = 30
popSize = N + 1
generation_max = 50
Cg = 0.7                # define Cg
Cp = 0.9                # define Cp
# Cw = 0.9              # define Cw
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)  # don't use scientific notation

In [15]:
import numpy as np
import numpy as np
import ClassicalPop
import QuantumPop
import globalFunc
import TaskQueue

def sort_task(task_queue, target_col=4):
    '''
    Initialize task_queue with Ai, Ri, Ci and Di for each real-time task i.
    array structure: [index, Ai, Ri, Ci, Di]
    array sorted parameter: [index->0, Ai->1, Ri->2, Ci->3, Di->4]
    '''
    return task_queue[np.argsort(task_queue[:, target_col])]

In [27]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
import math
import numpy as np
rot = np.empty([2, 2])
delta_theta = (1 / 2) * math.pi
radius = math.radians(delta_theta)
rot[0, 0] = math.cos(delta_theta)
rot[0, 1] = -math.sin(delta_theta)
rot[1, 0] = math.sin(delta_theta)
rot[1, 1] = math.cos(delta_theta)
rot

array([[ 6.123234e-17, -1.000000e+00],
       [ 1.000000e+00,  6.123234e-17]])

In [173]:
a_b = np.array([[1], [0]])
ans = a_b
print(a_b)
print()
print(ans)
theta = np.radians(45)
c, s = np.cos(theta), np.sin(theta)
R = np.array(((c, -s), (s, c)))
print(R) 
print(a_b)
print()
print(R[0, 0])
print(a_b[0, 0])
print(R[0, 1])
print(a_b[1, 0])
print(ans)
print()

print((rot[0, 0] * a_b[0, 0]) + (rot[0, 1] * a_b[1, 0]))
print((R[1, 0] * a_b[0, 0] + [1, 1] * a_b[1, 0]))
a = (R[0, 0] * a_b[0, 0]) + (R[0, 1] * a_b[1, 0])
b = (R[1, 0] * a_b[0, 0] + R[1, 1] * a_b[1, 0])

ans = np.array([[a], [b]])
ans


[[1]
 [0]]

[[1]
 [0]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[1]
 [0]]

0.7071067811865476
1
-0.7071067811865475
0
[[1]
 [0]]

6.123233995736766e-17
0.7071067811865475


array([[6.123234e-17],
       [1.000000e+00]])

In [153]:
theta = np.radians(45)
c, s = np.cos(theta), np.sin(theta)
R = np.array(((c, -s), (s, c)))
print(R)
print(a_b)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[1]
 [0]]


In [157]:

print(R[0, 0])
print(a_b[0, 0])
print(R[0, 1])
print(a_b[1, 0])

print((R[0, 0] * a_b[0, 0]) + (R[0, 1] * a_b[1, 0]))
print((R[1, 0] * a_b[0, 0] + R[1, 1] * a_b[1, 0]))

ans[0, 0] = (R[0, 0] * a_b[0, 0]) + (R[0, 1] * a_b[1, 0])
ans[1, 0] = (R[1, 0] * a_b[0, 0] + R[1, 1] * a_b[1, 0])



0.7071067811865476
0
-0.7071067811865475
0
0.0
0.0


In [155]:
ans[0, 0] = (R[0, 0] * a_b[0, 0]) + (R[0, 1] * a_b[1, 0])
ans[1, 0] = (R[1, 0] * a_b[0, 0] + R[1, 1] * a_b[1, 0])


In [200]:
a = np.cos(-0.01 * math.pi)

In [201]:
a

0.9995065603657316

In [33]:
a = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])
print(a.shape[0])

4


In [8]:
import math
print(math.cos(math.radians(180)))

-1.0
